# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\VADIM\Python\SFedU\third_term\knowledge_representation\lab_2\ui\lp_selection_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lp_selection_window(object):
    def setupUi(self, lp_selection_window):
        lp_selection_window.setObjectName("lp_selection_window")
        lp_selection_window.resize(503, 422)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lp_selection_window.sizePolicy().hasHeightForWidth())
        lp_selection_window.setSizePolicy(sizePolicy)
        lp_selection_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        lp_selection_window.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(lp_selection_window)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_lps = QtWidgets.QListWidget(lp_selection_window)
        self.list_lps.setMinimumSize(QtCore.QSize(0, 0))
        self.list_lps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_lps.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_lps.setObjectName("list_lps")
        self.verticalLayout.addWidget(self.list_lps)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_open = QtWidgets.QPushButton(lp_selection_window)
        self.button_open.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_open.setFont(font)
        self.button_open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_open.setIconSize(QtCore.QSize(24, 24))
        self.button_open.setObjectName("button_open")
        self.horizontalLayout.addWidget(self.button_open)
        self.button_delete = QtWidgets.QPushButton(lp_selection_window)
        self.button_delete.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_delete.setFont(font)
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_delete.setIconSize(QtCore.QSize(24, 24))
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.button_exit = QtWidgets.QPushButton(lp_selection_window)
        self.button_exit.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_exit.setFont(font)
        self.button_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_exit.setIconSize(QtCore.QSize(24, 24))
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout.addWidget(self.button_exit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(lp_selection_window)
        QtCore.QMetaObject.connectSlotsByName(lp_selection_window)

    def retranslateUi(self, lp_selection_window):
        _translate = QtCore.QCoreApplication.translate
        lp_selection_window.setWindowTitle(_translate("lp_selection_window", "Лингвистические переменные"))
        self.button_open.setText(_translate("lp_selection_window", "Открыть"))
        self.button_delete.setText(_translate("lp_selection_window", "Удалить"))
        self.button_exit.setText(_translate("lp_selection_window", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lp_selection_window = QtWidgets.QWidget()
    ui = Ui_lp_selection_window()
    ui.setupUi(lp_selection_window)
    lp_selection_window.show()
    sys.exit(app.exec_())
